# @author Team 42, Melbourne, Steven Tang, 832031
# @author Team 42, Chengdu, China, Qifan Deng, 1077479

version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    restart: always
    environment:
      TZ: "Australia/Melbourne"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/.docker/config.json:/config.json
    command: --interval 30
