---
# Configure and start watchtower, which monitor changes to images and auto
# restart containers

- name: Create watchtower directory
  become: yes
  file:
    path: '{{ watchtower.dir }}'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    recurse: yes
    state: directory

- name: Upload watchtower compose file
  copy:
    src: docker-compose.yml
    dest: '{{ watchtower.dir }}/docker-compose.yml'
    owner: ubuntu
    group: ubuntu
    mode: 0644

- name: Start watchtower
  docker_compose:
    project_src: '{{ watchtower.dir }}'
    pull: yes
    state: present
    remove_orphans: yes
    recreate: smart
