# @author Team 42, Melbourne, Steven Tang, 832031
# @author Team 42, Chengdu, China, Qifan Deng, 1077479

version: '3'
services:
  worker:
    image: registry.gitlab.com/comp90024/project-2:harvest
    environment:
      TZ: "Australia/Melbourne"
    command: "-r worker"
    networks:
        - couch_comp90024
    restart: on-failure
    volumes:
      - ./couchdb.json:/app/couchdb.json
      - ./harvest.json:/app/harvest.json
      - ./twitter.json:/app/twitter.json
    deploy:
      mode: replicated
      replicas: 2

networks:
  couch_comp90024:
    external: true
