---
# Get info about servers whose name starts with ins
- name: Get instance info
  tags: instance_info
  os_server_info:
    server: 'ins*'
  register: instance_info

- name: Create list of IPs
  tags: instance_info
  set_fact:
    instance_ips: "{{ instance_info.openstack_servers | map(attribute='public_v4') | list }}"

- debug:
    tags: instance_info
    msg: 'IPs: {{ instance_ips }}'

# Add hosts
- name: Add host
  tags: instance_info
  add_host:
    name: '{{ item }}'
    groups: COMP90024
  loop: '{{ instance_ips }}'
