---
# Run nginx servers using docker-compose
# Adapted from wordpress in week 5 materials

# Only applicable to first node
- name: Create directory
  run_once: true
  become: yes
  file:
    path: '{{ app_dir }}'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    recurse: yes
    state: directory

- name: Setup app
  run_once: true
  become: yes
  docker_compose:
    project_src: '{{ repository }}/app'
    pull: no
    state: present
    remove_orphans: yes
    recreate: smart
