# @author Team 42, Melbourne, Steven Tang, 832031

---
- name: Create app directory
  become: yes
  file:
    path: '{{ app.dir }}'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    recurse: yes
    state: directory

- name: Upload compose file
  template:
    src: docker-compose.yaml.j2
    dest: '{{ app.dir }}/docker-compose.yaml'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: Upload Caddyfile
  template:
    src: Caddyfile.j2
    dest: '{{ app.dir }}/Caddyfile'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

# Use docker-compose to up -d app
- name: Setup app
  docker_compose:
    project_src: '{{ app.dir }}'
    build: yes
    pull: yes
    state: present
    remove_orphans: yes
    recreate: smart
  register: setup_app
