# @author Team 42, Melbourne, Steven Tang, 832031

---
# Since internal vms require proxy to access external resources

- name: Create systemd docker directory
  become: yes
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Configure docker daemon proxy
  become: yes
  copy:
    src: http-proxy.conf
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    owner: root
    group: root
    mode: 0644

- name: Create .docker directory
  file:
    path: /home/ubuntu/.docker
    state: directory

- name: Configure docker client proxy
  become: yes
  copy:
    src: config.json
    dest: /home/ubuntu/.docker/config.json
    owner: ubuntu
    group: ubuntu
    mode: 0644
