---
# Basic tools
- name: Install utils
  become: yes
  apt:
    name: ['htop', 'git', 'python3', 'curl', 'wget', 'vim', 'python3-pip', 'jq', "vnstat", "socat", "gcc"]
    state: latest
    install-recommends: no
    update_cache: yes

# Install docker SDK
- name: pip docker SDK
  become: yes
  pip:
    name: docker

# Docker
# Adapted from, MIT license:
# https://docs.ansible.com/ansible/latest/modules/apt_repository_module.html
# https://github.com/nickjj/ansible-docker/blob/master/defaults/main.yml
# https://docs.docker.com/engine/install/ubuntu/
- name: Add docker gpg key
  become: yes
  apt_key:
    id: '9DC858229FC7DD38854AE2D88D81803C0EBFCD88'
    url: 'https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg'

# Add repository, but use eoan for now
- name: Add docker apt repository
  become: yes
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} eoan stable'
    state: present

- name: Install docker
  become: yes
  apt:
    name: ['docker-ce']
    state: latest
    update_cache: yes

- name: Install docker-compose
  become: yes
  pip:
    name: ['docker-compose']
    state: latest

- name: Add ubuntu to docker group
  become: yes
  user:
    name: 'ubuntu'
    groups: 'docker'
    append: 'yes'
