version: '3'
services:
  worker:
    build: ./
    environment:
      TZ: "Australia/Melbourne"
    command: "worker"
    networks:
        - couch_comp90024
    restart: on-failure
networks:
  couch_comp90024:
    external: true
