---
# Get cluster membership of nodes
- name: Get membership
  uri:
    url: 'http://{{ couch.user }}:{{ couch.password }}@127.0.0.1:5984/_membership'
    method: 'GET'
    return_content: yes
    force_basic_auth: yes
  register: couch_membership
  until: couch_membership.status == 200
  retries: 12
  delay: 5

- name: Map joined nodes to IPs
  run_once: true
  set_fact:
    couch_cluster_nodes: "{{ couch_membership.json.cluster_nodes | regex_replace('couchdb@') }}"
