---
# Removes nodes from cluster
- name: Get info about node to remove
  uri:
    url: 'http://{{ couch.user }}:{{ couch.password }}@127.0.0.1:5984/_node/_local/_nodes/couchdb@{{ item }}'
    method: 'GET'
    body_format: json
    force_basic_auth: yes
    status_code: [200, 201, 404]
  register: node_document
  when: 'item != inventory_hostname'

# https://docs.couchdb.org/en/master/cluster/nodes.html#removing-a-node
- name: Remove node
  uri:
    url: 'http://{{ couch.user }}:{{ couch.password }}@127.0.0.1:5984/_node/_local/_nodes/couchdb@{{ item }}?rev={{ node_document.json._rev }}'
    method: 'DELETE'
    body_format: json
    force_basic_auth: yes
  when: 'item != inventory_hostname and node_document.status != 404'
