# @author Team 42, Melbourne, Steven Tang, 832031

---
# Creates volumes

- name: Create volume
  os_volume:
    display_name: '{{ item.display_name }}'
    availability_zone: '{{ availability_zone }}'
    size: '{{ item.size }}'
    state: present
    wait: yes
  loop: '{{ volumes }}'
