# @author Team 42, Melbourne, Steven Tang, 832031

---
# Login to container registry
- name: Login to registry
  docker_login:
    registry: '{{ registry.url }}'
    username: '{{ registry.username }}'
    password: '{{ registry.password }}'
