---
# Initiate instances

- name: Create instance
  os_server:
    name: '{{ item.name }}'
    availability_zone: '{{ availability_zone }}'
    # Base image
    image: '{{ instance.image }}'
    # Flavor
    flavor: '{{ instance.flavor }}'
    # SSH key name
    key_name: '{{ key_name }}'
    # Security group
    security_groups: '{{ security_groups | map(attribute="name") | list }}'
    # Volume
    volumes: '{{ item.volumes }}'
    # Network
    network: '{{ instance.network }}'
    auto_floating_ip: yes
    timeout: 600
    wait: yes
    state: present
  loop: '{{ instances }}'
  register: os_instance

- name: Wait for connection
  wait_for:
    host: "{{ item.openstack.public_v4 }}"
    port: 22
    timeout: 120
    search_regex: OpenSSH
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined
