---
- name: Create mapreduce directory
  become: yes
  file:
    path: '{{ mapreduce.dir }}'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    recurse: yes
    state: directory

- name: Upload mapreduce docker file
  copy:
    src: docker-compose.yml
    dest: '{{ mapreduce.dir }}/docker-compose.yml'
    owner: ubuntu
    group: ubuntu
    mode: 0644

- name: Upload mapreduce couch config
  template:
    src: couchdb.json.j2
    dest: '{{ mapreduce.dir }}/couchdb.json'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: Run mapreduce on first node
  docker_compose:
    project_src: '{{ mapreduce.dir }}'
    build: yes
    state: present
    remove_orphans: yes
