---
# Run nginx servers using docker-compose
# Adapted from wordpress in week 5 materials

- name: Create directory
  become: yes
  file:
    path: '{{ nginx_dir }}'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    recurse: yes
    state: directory

- name: Upload compose file
  become: yes
  template:
    src: docker-compose.yaml.j2
    dest: '{{ nginx_dir }}/docker-compose.yaml'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: Setup nginx
  become: yes
  docker_compose:
    project_src: '{{ nginx_dir }}'
    pull: yes
    state: present
    remove_orphans: yes
    recreate: smart
