# @author Team 42, Melbourne, Steven Tang, 832031

---
# Security groups
# - name: List security groups
#   debug: msg="{{ security_groups | map(attribute='name') | list }}"

# Create security group
- name: Create security group
  os_security_group:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    state: present
  loop: '{{ security_groups }}'

# Create egress ruels
- name: Create egress rule
  os_security_group_rule:
    security_group: 'default'
    ethertype: 'IPv4'
    direction: 'egress'
    remote_ip_prefix: '0.0.0.0/0'
    state: present

# Create security group rules
- name: Create security group rules
  os_security_group_rule:
    security_group: '{{ item.0.name }}'
    protocol: '{{ item.1.protocol }}'
    port_range_min: '{{ item.1.port_range_min }}'
    port_range_max: '{{ item.1.port_range_max }}'
    remote_ip_prefix: '{{ item.1.remote_ip_prefix }}'
    state: present
  with_subelements:
    - '{{ security_groups }}'
    - rules
