- name: Provision VMs
  hosts: localhost
  gather_facts: no
  # variables (how to provision)
  vars_files:
    - vars/openstack.yaml
  roles:
    # security groups
    - role: openstack/security-group
    # volumes
    - role: openstack/volume
    # instance
    - role: openstack/instance
    # instance info
    - role: openstack/instance-info

- name: Set up VMs
  hosts: COMP90024
  gather_facts: yes
  strategy: free
  tags:
    - server-setup
  vars_files:
    - vars/configure.yaml
  roles:
    # proxy in /etc/environment
    - role: server-setup/proxy
    # Upload public keys and private deploy key
    - role: server-setup/upload-keys
    # Mount volumes
    - role: server-setup/mount-volume
    # Install utils, docker, compose
    - role: server-setup/install-dependencies
    # Proxy
    - role: server-setup/docker-proxy
    # Restart Docker
    - role: server-setup/restart-docker

- name: Setup couch
  hosts: COMP90024
  gather_facts: no
  order: sorted
  tags:
    - configure
  vars_files:
    - vars/configure.yaml
  roles:
    # Clone repository
    - role: deploy/clone
    # Setup couch
    - role: deploy/couch

- name: Setup app and harvester
  hosts: COMP90024
  gather_facts: no
  strategy: free
  order: sorted
  tags:
    - configure
  vars_files:
    - vars/configure.yaml
  roles:
    # Setup app
    - role: deploy/app
    # Setup harvesters
    - role: deploy/harvest
