# Provision instances on localhost
- hosts: localhost
  # load module for gathering useful variables about remote hosts
  gather_facts: true

  # variables (how to provision)
  vars_files:
    - vars/openstack.yaml

  roles:
    # security groups
    - role: openstack/security-group
    # volumes
    - role: openstack/volume
    # instance
    - role: openstack/instance
    # instance info
    - role: openstack/instance-info
    # attach volume
    - role: openstack/refresh-configuration

# Setup servers
- hosts: COMP90024
  order: sorted
  tags:
    - server-setup
  vars_files:
    - vars/configure.yaml

  roles:
    # Upload public keys and private deploy key
    - role: server-setup/upload-keys
    # Proxy in /etc/environment
    - role: openstack/proxy
    # Mount volumes
    - role: server-setup/mount-volume
    # Install docker, compose
    - role: server-setup/install-dependencies
    # Proxy
    - role: server-setup/docker-proxy

# Deploy applications
- hosts: COMP90024
  order: sorted
  tags:
    - configure
  vars_files:
    - vars/configure.yaml

  roles:
    # Shutdown all apps and prune (for debugging)
    # - role: deploy/down
    # Clone repository
    - role: deploy/clone
    # Setup couch
    - role: deploy/couch
    # Setup app
    - role: deploy/app
    # Setup harvesters
    - role: deploy/harvest
