# Provision instances on localhost
- hosts: localhost

  # load module for gathering useful variables about remote hosts
  gather_facts: true

  # variables (how to provision)
  vars_files:
    - vars/openstack.yaml

  roles:
    # prepares local machine
    - role: openstack/prepare-local
    # security groups
    - role: openstack/security-group
    # volumes
    - role: openstack/volume
    # instance
    - role: openstack/instance
    # instance info
    - role: openstack/instance-info
    # attach volume
    - role: openstack/refresh-configuration

# Configure instances
- hosts: COMP90024
  tags:
    - configure
  vars_files:
    - vars/configure.yaml

  roles:
    # Upload public keys
    - role: server/upload-keys
    # Install docker, and other useful utils
    - role: server/install-dependencies
    # Mount volumes
    - role: server/mount-volume
    # Restart docker to let it use new volume
    - role: server/restart-docker
    # Install nginx
    - role: server/nginx
