---
# Deploys harvesters
- set_fact:
    master_ip: '{{ groups["COMP90024"][0] }}'

# Upload worker files
- name: Upload worker compose file
  become: yes
  template:
    src: docker-compose.yaml.j2
    dest: '{{ repository.dest }}/harvest/docker-compose-master.yml'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: Upload couchdb config of harvesters
  become: yes
  template:
    src: couchdb.json.j2
    dest: '{{ repository.dest }}/harvest/couchdb.json'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: Start master and worker on head node
  run_once: true
  docker_compose:
    files: ['docker-compose-master.yml', 'docker-compose.yml']
    project_src: '{{ repository.dest }}/harvest'
    build: yes
    state: present
    remove_orphans: yes
    recreate: smart

- name: Start workers on other nodes
  docker_compose:
    project_src: '{{ repository.dest }}/harvest'
    build: yes
    state: present
    remove_orphans: yes
    recreate: smart
  when: 'groups["COMP90024"][0] != inventory_hostname'
