---
- name: Create harvest directory
  become: yes
  file:
    path: '{{ harvest.dir }}'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    recurse: yes
    state: directory

- name: Upload master compose file
  template:
    src: docker-compose.yml.j2
    dest: '{{ harvest.dir }}/docker-compose-master.yml'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: Upload worker compose file
  copy:
    src: docker-compose.yml
    dest: '{{ harvest.dir }}/docker-compose.yml'
    owner: ubuntu
    group: ubuntu
    mode: 0644

- name: Upload couchdb config of harvesters
  template:
    src: couchdb.json.j2
    dest: '{{ harvest.dir }}/couchdb.json'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: Upload harvest config of harvesters
  copy:
    src: '{{ playbook_dir }}/../harvest/harvest.json'
    dest: '{{ harvest.dir }}/harvest.json'

- name: Upload twitter config of harvesters
  copy:
    src: '{{ playbook_dir }}/../harvest/twitter.json'
    dest: '{{ harvest.dir }}/twitter.json'

- name: Start master and worker on first node
  docker_compose:
    files: ['docker-compose-master.yml', 'docker-compose.yml']
    project_src: '{{ harvest.dir }}'
    build: yes
    state: present
    remove_orphans: yes
    recreate: smart
  when: 'groups["COMP90024"][0] == inventory_hostname'

- name: Start workers on other nodes
  docker_compose:
    project_src: '{{ harvest.dir }}'
    build: yes
    state: present
    remove_orphans: yes
    recreate: smart
  when: 'groups["COMP90024"][0] != inventory_hostname'
