name: Builds harvest and app images

# Adapted from:
# https://www.prestonlamb.com/blog/creating-a-docker-image-with-github-actions
# on:
#   push:
#     branches:
#       - master

# Trigger only when starred
on:
  watch:
    types: [started]

jobs:
  build_harvest:
    runs-on: ubuntu-latest
    env:
      working-directory: ./harvest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Gitlab Registry
        run: echo ${{ secrets.REG_PASS }} | docker login registry.gitlab.com -u ${{ secrets.REG_USER }} --password-stdin
      - name: Build harvest image
        run: docker build . -t registry.gitlab.com/comp90024/project-2:harvest
      - name: Push docker image
        run: docker push registry.gitlab.com/comp90024/project-2:harvest

  build_app:
    runs-on: ubuntu-latest
    env:
      working-directory: ./app
    steps:
      - uses: actions/checkout@v2
      - name: Login to Gitlab Registry
        run: echo ${{ secrets.REG_PASS }} | docker login registry.gitlab.com -u ${{ secrets.REG_USER }} --password-stdin
      - name: Build app image
        run: docker build . -t registry.gitlab.com/comp90024/project-2:app
      - name: Push docker image
        run: docker push registry.gitlab.com/comp90024/project-2:app
